### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by GHeeJeon** [chom-cracker/chom-cracker#3]
- [ ] 맵 병합
- [ ] 조명(빛) 렌더링 다시 하기
- [ ] 시작화면 종료화면 UI
- [ ] 서버 구축
- [ ] 광클게임 레퍼런스 찾기
- [ ] 멀티플레이 레퍼런스 찾기
- [ ] 프로토타입-직선코스 만들어보기(클릭(터치)하면 정해진 방향으로 가속)
